"""add transction staging table

Revision ID: 032c20e287a4
Revises: 62db1aeddc22
Create Date: 2026-05-17 09:13:19.976285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032c20e287a4'
down_revision = '62db1aeddc22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contractor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_staging')
    # ### end Alembic commands ###
