"""budgets: unikalny plan na kategorie w miesiacu

Revision ID: 182c9e0f39ec
Revises: ec9b5fd33e72
Create Date: 2026-09-04 08:08:33.987505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182c9e0f39ec'
down_revision = 'ec9b5fd33e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_budget_user_okres_kategoria', ['user_token', 'year', 'month', 'category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_budget_user_okres_kategoria', type_='unique')

    # ### end Alembic commands ###
