"""dodanie tabeli statement_imports (historia importow wyciagow)

Revision ID: 264190fff00f
Revises: c8a3e1f6b902
Create Date: 2026-07-20 07:58:07.392744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264190fff00f'
down_revision = 'c8a3e1f6b902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_token', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('bank', sa.String(length=30), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_token'], ['users.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statement_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statement_imports_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statement_imports_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statement_imports_user_token'), ['user_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statement_imports_user_token'))
        batch_op.drop_index(batch_op.f('ix_statement_imports_batch_id'))
        batch_op.drop_index(batch_op.f('ix_statement_imports_account_id'))

    op.drop_table('statement_imports')
    # ### end Alembic commands ###
