"""account_type na koncie (typy: ROR/KO/Kredyt/Rach. Maklerski/IKZE)

Revision ID: 2edba3c2f990
Revises: 264190fff00f
Create Date: 2026-07-26 19:20:05.613661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edba3c2f990'
down_revision = '264190fff00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
