"""origin transakcji

Revision ID: 3923305e558c
Revises: 482b348b2b66
Create Date: 2026-08-11 09:52:01.365795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3923305e558c'
down_revision = '482b348b2b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=20), server_default='manual', nullable=False))

    # ### end Alembic commands ###

    # Backfill danych historycznych. Rozróżnienia "ręcznie vs import" nie da się
    # odtworzyć wstecz (brak jakiegokolwiek śladu w wierszu) — takie transakcje
    # dostają 'unknown', a nie mylące 'manual'.
    op.execute("UPDATE transactions SET origin = 'unknown'")
    op.execute("""
        UPDATE transactions SET origin = 'reconcile'
        WHERE category_id IN (SELECT id FROM categories WHERE type = 'system_reconciliation')
    """)
    op.execute("UPDATE transactions SET origin = 'planned' WHERE source_planned_id IS NOT NULL")
    op.execute("UPDATE transactions SET origin = 'recurring' WHERE source_recurring_id IS NOT NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
