"""kategoria banku w poczekalni

Revision ID: 451d30fccbfa
Revises: 182c9e0f39ec
Create Date: 2026-09-26 14:14:27.277442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451d30fccbfa'
down_revision = '182c9e0f39ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_staging', schema=None) as batch_op:
        batch_op.drop_column('bank_category')

    # ### end Alembic commands ###
