"""feat: add comment field to transactions

Revision ID: 4904814893ed
Revises: a13d2b0a84f7
Create Date: 2026-06-15 19:10:44.049255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4904814893ed'
down_revision = 'a13d2b0a84f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
