"""dodanie kolumny sort_order do tabeli accounts

Revision ID: 4b85c5d7b8c2
Revises: 9f65e18a9b83
Create Date: 2026-07-12 22:19:59.546889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b85c5d7b8c2'
down_revision = '9f65e18a9b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###

    # Backfill: zachowaj dotychczasową kolejność (alfabetyczną) jako sort_order,
    # osobno dla każdego użytkownika — żeby po migracji lista kont nie "skoczyła".
    conn = op.get_bind()
    users = conn.execute(sa.text('SELECT DISTINCT user_token FROM accounts')).fetchall()
    for (user_token,) in users:
        rows = conn.execute(
            sa.text('SELECT id FROM accounts WHERE user_token = :ut ORDER BY name'),
            {'ut': user_token}
        ).fetchall()
        for position, (acc_id,) in enumerate(rows):
            conn.execute(
                sa.text('UPDATE accounts SET sort_order = :so WHERE id = :id'),
                {'so': position, 'id': acc_id}
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
