"""add user_id to budget

Revision ID: 639f42d22d1a
Revises: 032c20e287a4
Create Date: 2026-05-17 10:50:58.702144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639f42d22d1a'
down_revision = '032c20e287a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
