"""Add suggested_contractor_name to TransactionStaging

Revision ID: 79344ae08191
Revises: ef6be4aa34bc
Create Date: 2026-06-10 22:26:48.675526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79344ae08191'
down_revision = 'ef6be4aa34bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_contractor_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_staging', schema=None) as batch_op:
        batch_op.drop_column('suggested_contractor_name')

    # ### end Alembic commands ###
