"""add owner and co_owner to accounts

Revision ID: 9f65e18a9b83
Revises: ff31a25950c9
Create Date: 2026-06-20 22:23:43.343372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f65e18a9b83'
down_revision = 'ff31a25950c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('co_owner', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('co_owner')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
