"""Add is_system_category to Category model

Revision ID: a33a724a9b44
Revises: e9e0c1a0ed64
Create Date: 2026-05-18 23:01:07.508487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33a724a9b44'
down_revision = 'e9e0c1a0ed64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system_category', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_system_category')

    # ### end Alembic commands ###
