"""add updated_at to transactions

Revision ID: af8de7b9064b
Revises: 1b73085edf39
Create Date: 2026-05-17 11:55:47.676335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8de7b9064b'
down_revision = '1b73085edf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('transaction_staging', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
