"""add is_active to contractor

Revision ID: d1cfb9b68881
Revises: d601d8093880
Create Date: 2026-05-17 20:13:31.605304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cfb9b68881'
down_revision = 'd601d8093880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
