"""add contractor_id to archive

Revision ID: d601d8093880
Revises: af8de7b9064b
Create Date: 2026-05-17 14:47:53.908666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd601d8093880'
down_revision = 'af8de7b9064b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mapping_rules', sa.String(length=500), nullable=True),
    sa.Column('default_category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contractor_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('transaction_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposed_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proposed_contractor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['proposed_category_id'], ['id'])
        batch_op.create_foreign_key(None, 'contractors', ['proposed_contractor_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contractor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'contractors', ['contractor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contractor_id')

    with op.batch_alter_table('transaction_staging', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proposed_contractor_id')
        batch_op.drop_column('proposed_category_id')

    with op.batch_alter_table('transaction_archive', schema=None) as batch_op:
        batch_op.drop_column('contractor_id')

    op.drop_table('contractors')
    # ### end Alembic commands ###
