"""dodaj counterparty_account do TransactionStaging

Revision ID: e21ba7cff2e7
Revises: 2edba3c2f990
Create Date: 2026-07-27 18:54:51.283169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21ba7cff2e7'
down_revision = '2edba3c2f990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counterparty_account', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_staging', schema=None) as batch_op:
        batch_op.drop_column('counterparty_account')

    # ### end Alembic commands ###
