"""Dodanie kolumny is_default do tabeli accounts

Revision ID: e9e0c1a0ed64
Revises: 1d02c93172f3
Create Date: 2026-05-18 13:49:21.780205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e0c1a0ed64'
down_revision = '1d02c93172f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
